package kotlin.reflect.jvm.internal;

import androidx.datastore.preferences.PreferencesProto$Value;
import kotlin.Metadata;
import kotlin.NoWhenBranchMatchedException;
import kotlin.jvm.internal.Lambda;
import kotlin.reflect.jvm.internal.KClassImpl;
import kotlin.reflect.jvm.internal.KDeclarationContainerImpl;
import kotlin.reflect.jvm.internal.impl.descriptors.FindClassInModuleKt;
import kotlin.reflect.jvm.internal.impl.load.kotlin.header.KotlinClassHeader;
import q8.e;

@Metadata(d1 = {"\u0000\u000e\n\u0002\u0010\u0000\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0004\u0010\u0006\u001a\n \u0003*\u0004\u0018\u00010\u00020\u0002\"\b\b\u0000\u0010\u0001*\u00020\u0000H\n¢\u0006\u0004\b\u0004\u0010\u0005"}, d2 = {"", "T", "Ll8/b;", "kotlin.jvm.PlatformType", "invoke", "()Ll8/b;", "<anonymous>"}, k = PreferencesProto$Value.INTEGER_FIELD_NUMBER, mv = {1, 8, 0})
/* loaded from: classes.dex */
public final class KClassImpl$Data$descriptor$2 extends Lambda implements u7.a<l8.b> {

    /* renamed from: j  reason: collision with root package name */
    public final /* synthetic */ KClassImpl<T> f13123j;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public KClassImpl$Data$descriptor$2(KClassImpl<T> kClassImpl) {
        super(0);
        this.f13123j = kClassImpl;
    }

    @Override // u7.a
    public final l8.b k0() {
        l8.b a10;
        KotlinClassHeader.Kind kind;
        int i10;
        KotlinClassHeader kotlinClassHeader;
        int i11 = KClassImpl.f13103l;
        KClassImpl<T> kClassImpl = this.f13123j;
        h9.b r3 = kClassImpl.r();
        KClassImpl<T>.Data k02 = kClassImpl.f13105k.k0();
        k02.getClass();
        c8.j<Object> jVar = KDeclarationContainerImpl.Data.f13143b[0];
        Object k03 = k02.f13144a.k0();
        v7.g.e(k03, "<get-moduleData>(...)");
        boolean z10 = r3.c;
        u9.e eVar = ((q8.h) k03).f16955a;
        if (z10) {
            a10 = eVar.b(r3);
        } else {
            a10 = FindClassInModuleKt.a(eVar.f17902b, r3);
        }
        if (a10 == null) {
            Class<T> cls = kClassImpl.f13104j;
            q8.e a11 = e.a.a(cls);
            if (a11 != null && (kotlinClassHeader = a11.f16951b) != null) {
                kind = kotlinClassHeader.f13953a;
            } else {
                kind = null;
            }
            if (kind == null) {
                i10 = -1;
            } else {
                i10 = KClassImpl.a.f13139a[kind.ordinal()];
            }
            switch (i10) {
                case -1:
                case 6:
                    throw new KotlinReflectionInternalError("Unresolved class: " + cls);
                case 0:
                default:
                    throw new NoWhenBranchMatchedException();
                case 1:
                case PreferencesProto$Value.FLOAT_FIELD_NUMBER /* 2 */:
                case PreferencesProto$Value.INTEGER_FIELD_NUMBER /* 3 */:
                    throw new UnsupportedOperationException("Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: " + cls);
                case PreferencesProto$Value.LONG_FIELD_NUMBER /* 4 */:
                    throw new UnsupportedOperationException("This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: " + cls);
                case 5:
                    throw new KotlinReflectionInternalError("Unknown class: " + cls + " (kind = " + kind + ')');
            }
        }
        return a10;
    }
}
